4 create a simpler dalvik parser
Fare9/Shuriken-Analyzer pull request #10
Opened 2023-12-29 17:34 UTC by Fare9

Added the code for a simple dex parser into Shuriken, the code is a simplified version of Kunai's dex parser (some parts of the code were simplified), added a couple of tests together with DEX files.

2024-01-07 14:23 UTC, jeppojeps commented on shuriken/include/shuriken/parser/Dex/classes.h
I know it's probably impossible to change this, but the name classes is messing up the intrinsic meaning of class of c++ with .class or the .dex of Java, probably we need to put some extra disclaimer in the documentation. At a first glance when I opened the file somehow I interpreted it as these are the classes of the project i.e. the structures that you define to make the parser (c++ classes)

2024-01-07 14:33 UTC, jeppojeps requested changes
I have been looking at the code in the last 10 days a few times it seems RAII is respected and also the usage of smart pointers is fine. I'd try to improve naming and structure of files and some extra documentation. It will help readability.

2024-01-07 14:33 UTC, jeppojeps commented on shuriken/include/shuriken/parser/Dex/classes.h
maybe dvm_classes?

2024-01-07 14:33 UTC, jeppojeps commented on shuriken/include/shuriken/parser/Dex/fields.h
same goes here, it can be confusing, cause these are fields of dvm or fields you define for the parser?

2024-01-07 14:33 UTC, jeppojeps commented on shuriken/include/shuriken/parser/Dex/header.h
same here

2024-01-07 14:33 UTC, jeppojeps commented on shuriken/include/shuriken/parser/Dex/mapitem.h
OK now, here is the other way around, an item is a dalvik concept or some abstraction of shuriken?

2024-01-07 14:33 UTC, jeppojeps commented on shuriken/include/shuriken/parser/Dex/methods.h
dvm_methods?

2024-01-07 14:33 UTC, jeppojeps commented on shuriken/include/shuriken/parser/Dex/parser.h
dex_parser, dvm_parser...I'd use a less generic name

2024-01-07 14:33 UTC, jeppojeps commented on shuriken/include/shuriken/parser/Dex/protos.h
I think I explained myself, just take it with a grain of salt, but names help

2024-01-07 14:33 UTC, jeppojeps commented on shuriken/include/shuriken/parser/Dex/types.h
Now this file how differs from the dvm_types?

2024-01-07 14:33 UTC, jeppojeps commented on shuriken/lib/parser/Dex/classes.cpp
here it becomes clear to me, now classes.cpp as a file name makes me feel I am lost, are these dvm classes, are these internal classes of Shuriken?

2024-01-07 14:33 UTC, jeppojeps commented on shuriken/tests/code/java/_cast.java
now we use _ notation I think these things need to be explained so the code will be easy to read and interpret

2024-01-07 14:33 UTC, jeppojeps commented on shuriken/tests/code/java/_double.java
now _cast seems a bit messy cause it's an operator while _double it's a type, so with _ what are we defining and why we use the _

2024-01-08 18:10 UTC, Fare9 commented on shuriken/tests/code/java/_cast.java
these files are taken from another project, so their name is kept and have not been modified.

2024-01-08 18:11 UTC, Fare9 commented
The files have been renamed as well as the main classes from the DEX data. @jeppojeps

2024-01-08 19:53 UTC, merged